clusterName: homelab
talosVersion: v1.10.5
kubernetesVersion: v1.32.5
endpoint: https://192.168.221.172:6443

nodes:
  - hostname: talos-master
    ipAddress: 192.168.221.172
    controlPlane: true
    installDisk: /dev/sda
    machineSpec:
      mode: metal
  - hostname: talos-worker
    ipAddress: 192.168.221.184
    controlPlane: false
    installDisk: /dev/sda
    machineSpec:
      mode: metal

worker:
  nodeLabels:
    node-role.kubernetes.io/worker: ""
