[heritage]
heritage ansible_host=TOFU_OUTPUT_IP ansible_user=root

[talos:children]
talos_master
talos_worker

[talos_master]
talos-master ansible_host=TOFU_OUTPUT_IP ansible_connection=local

[talos_worker]
talos-worker ansible_host=TOFU_OUTPUT_IP ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
