[heritage_hosts]
heritage ansible_host=192.168.221.214 ansible_user=root

[talos:children]
talos_master
talos_worker

[talos_master]
talos-master ansible_host=192.168.221.172 ansible_connection=local

[talos_worker]
talos-worker ansible_host=192.168.221.184 ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
