[proxmox_hosts]
walle ansible_host=walle.bun-bull.ts.net ansible_user=crong ansible_become=true

[heritage_hosts]
heritage ansible_host=192.168.221.214 ansible_user=root

[cockpit_hosts]
cockpit ansible_host=192.168.221.117 ansible_user=ubuntu ansible_become=true ansible_ssh_common_args='-J crong@walle.bun-bull.ts.net'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
