---
- name: Restart cockpit.socket
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
