---
- Infrastructure:
    - Proxmox:
        - abbr: PVE
          href: https://walle.bun-bull.ts.net
    - Tailscale:
        - abbr: TS
          href: https://login.tailscale.com/admin/machines
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com

- Developer:
    - homelab:
        - abbr: HL
          href: https://github.com/deuxksy/homelab
    - Github:
        - abbr: GH
          href: https://github.com/deuxksy
    - sylph:
        - abbr: SY
          href: https://github.com/deuxksy/sylph
