#ENC[AES256_GCM,data:QxDbSJR7GBY76YnspLstcAdTWptOtZtrikieR2xTXXmLazShU1Ff/EsofcGjHQM+q1QOR4y7YTAJiWpAkl5gLFCD2eQds4j9T4K2JQ==,iv:HJhm2Fo/A06ekpzoSz/RlpsxsLuCro7IQNeoqyzEVYg=,tag:94Vh6IXizqb0WWmSyHVbEg==,type:comment]
#ENC[AES256_GCM,data:mq5Hd9Q7PLYjL2MuzcPRkCGagTlcp3VsBR2qQXeNaInHAbB5bDmhzAKxmzEN1H7WCXEs3LnBFa/1nFI2yx8YAenjnG1hSgKAI6hQQQ2gCxqcJfVN,iv:p3ucOouAV+NGG6iq8LM2QhqveQ5kk1tBozMJGMjfOHs=,tag:C0eJBJ8XIUvMl57XSY6frg==,type:comment]
cockpit_admin_password: ENC[AES256_GCM,data:3EUaKtVH,iv:lz4S8/UlX5VamMwnCl1V+n7cjhYqWs8oEcz1xymNNWs=,tag:qAc/dlqBjd6/+EaxzkMR7Q==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:aYbIcEolIAavYCrq20+JPb2CHtCET9EoSWw9D9/784W40L/3+ncLYVEv9aVCLqxN+Ra+X/s1oQXFI03xbQ==,iv:d5aLF5whh6Uc5XpPm/cAeBs6JSRZjRAAkAoYwF6iEos=,tag:Pe0NoQcxThccD2StIKrDgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSkhtWkE0VjRjbS90QWR3
            Yk4zZkNFODhuZUR3SHdiYTMrMlQwSTFObGprCkFXWHFLQ3YyenUzZHlpSGY4cjhC
            eUNTN29KSGU4Z3gxZTNzWGJYSnlsWXMKLS0tIDZXSDdHSDN4aFYydmg5MFdIWDc4
            cGhxL3Zhc1Z2NmtzWmhXMUNpY1ZVOWsKuZbSxNZtjnJb2Ei45S5WVNm5j6vkQ+Nr
            cHkcKqtOCfrY/1i4FoChKtI8MxNEvUCmm/v+U6J9Cr/3AVtJunqTpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw643dna4spaup6sr5ap0jf039ncjd54e8ekvrfy6p6x96ys2y4qn5vcsy
    lastmodified: "2026-07-05T16:17:34Z"
    mac: ENC[AES256_GCM,data:RPIBU346YQkGpenJyh2XQcBrtfHGDqbWGPyw1WO688pHiNKeip82f74yzVkBIyuPbnRQct9XeY8/CKtGzINU58L2nS/EQrd3/K0FW8JeJk3EhcPe/gjcDE8ps36aLhGED51YD37IQ0KAaax7RkfiLeEpEJC9AfzYoUaRJ3O8DbA=,iv:RJ7pZ4KA+AjnRlFkKaluENkJoN1iXsKOtYNys1Rp92w=,tag:gioG6Ltok1H0qb84vCMn7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
