#ENC[AES256_GCM,data:QxDbSJR7GBY76YnspLstcAdTWptOtZtrikieR2xTXXmLazShU1Ff/EsofcGjHQM+q1QOR4y7YTAJiWpAkl5gLFCD2eQds4j9T4K2JQ==,iv:HJhm2Fo/A06ekpzoSz/RlpsxsLuCro7IQNeoqyzEVYg=,tag:94Vh6IXizqb0WWmSyHVbEg==,type:comment]
#ENC[AES256_GCM,data:mq5Hd9Q7PLYjL2MuzcPRkCGagTlcp3VsBR2qQXeNaInHAbB5bDmhzAKxmzEN1H7WCXEs3LnBFa/1nFI2yx8YAenjnG1hSgKAI6hQQQ2gCxqcJfVN,iv:p3ucOouAV+NGG6iq8LM2QhqveQ5kk1tBozMJGMjfOHs=,tag:C0eJBJ8XIUvMl57XSY6frg==,type:comment]
cockpit_admin_password: ENC[AES256_GCM,data:MPVK+W9+5ATJ,iv:zpr+24B1LQr7jBciX9zMZS8qTsguIkM1A4mAXLaW27E=,tag:1MnNU9bMsROOiPnAjertqQ==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:AspVQT5TUBZ4+Pa996q/iIgGx9M=,iv:/eEIqrEFEUG8XNUQx51E/4db8LtoaZfrwx+ILZtsIMY=,tag:yYp8LD2sGErZULu0Ifbr4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSkhtWkE0VjRjbS90QWR3
            Yk4zZkNFODhuZUR3SHdiYTMrMlQwSTFObGprCkFXWHFLQ3YyenUzZHlpSGY4cjhC
            eUNTN29KSGU4Z3gxZTNzWGJYSnlsWXMKLS0tIDZXSDdHSDN4aFYydmg5MFdIWDc4
            cGhxL3Zhc1Z2NmtzWmhXMUNpY1ZVOWsKuZbSxNZtjnJb2Ei45S5WVNm5j6vkQ+Nr
            cHkcKqtOCfrY/1i4FoChKtI8MxNEvUCmm/v+U6J9Cr/3AVtJunqTpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw643dna4spaup6sr5ap0jf039ncjd54e8ekvrfy6p6x96ys2y4qn5vcsy
    lastmodified: "2026-07-05T15:53:46Z"
    mac: ENC[AES256_GCM,data:Osizv2QoJkccxPSE+E7ZdIC/NTjZhmMim9RADLG/7HEGNAgbZE22sJhlaD/H4uc3AzXIziQdQ27KMe82BmIp3OpTfBdYsdsF5pVylEK9p0T9084dkt5p42p8xA3GIFeJwMS9NwypImi3inBAEIKcamOVyVy8ICDm9I6WUTO3z1E=,iv:yAF2MtHsnwIN9S29CmenHlSoG/awxcxfMHFG/WA0ceQ=,tag:U9NyUTcVmUBPy5t823W+7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
